-- Optional safety check only. Run in Supabase SQL Editor if Save/Enquiry gives column errors.
-- This does not delete data.

create table if not exists public.products (
  product_id text primary key,
  product_name text,
  category text,
  image_key text,
  display_order int,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.product_rates (
  id bigint generated by default as identity primary key,
  product_id text references public.products(product_id) on delete cascade,
  type text,
  grade text,
  specification text,
  size_thickness text,
  rate text,
  unit text,
  valid_upto text,
  remarks text,
  display_order int,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.site_settings (
  setting_key text primary key,
  setting_value text,
  updated_at timestamptz default now()
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text,
  company text,
  gst text,
  city text,
  mobile text,
  email text,
  product text,
  requirement text,
  created_at timestamptz default now()
);

alter table public.products enable row level security;
alter table public.product_rates enable row level security;
alter table public.site_settings enable row level security;
alter table public.enquiries enable row level security;
